
CREATE VIEW VIEW_CGGXXZJL AS
SELECT 
    JL.RID,
    JL.XMMC,
    u.REALNAME as XZR,
    JL.XZSJ,
    JL.CLIENTIP,
    JL.FILENAME,
    CONCAT(ROUND(JL.FILESIZE / 1024 / 1024, 2), ' MB') AS FILESIZE,
    JL.FILEPATH
FROM PROJ_CGGXJL JL
left join userinfo u on u.USERID = JL.XZRID 
WHERE JL.XTMC = '成果共享子系统';